/* export const products = [
    {
      "id": 1,
      "stock": 0,
      "priceNow": 899.99,
      "priceBefore": 999.99,
      "title": "AK-12",
      "description": "The AK-12, Avtomat Kalashnikova, 2012 (GRAU index 6P70) is a Russian assault rifle chambered in 5.45x39mm designed and manufactured by the Kalashnikov Concern (formerly Izhmash), making it the fifth generation of Kalashnikov rifles",
      "completeDescription": "The most conspicuous identifying feature of the AN-94 is its magazine which is canted several degrees to the right of center (when viewed from a firing position). This design feature is necessary to accommodate the unique ammunition feed mechanism. The AN-94 is chambered in the same 5.45×39mm M74 cartridge as the AK-74, and it utilizes a rotating bolt to lock the action. Gennadiy Nikonov and his engineers used the Russian term Smeschennyi Impuls Svobodnogo Zatvora to describe the rifles method of operation, meaning recoil shifted pulse.",
      "category": "assault-riffle",
      "img": "https://res.cloudinary.com/dndvrsb0w/image/upload/v1686697704/tfb-55_mgmqsb.jpg",
      "rate": "⭐⭐⭐⭐⭐",
      "credit": "Payments as low as $40.38 / month",
      "stockDetail": "Very Low Stock",
      "shipping": "Ships in 20 to 40 business days",
      "fullName": "Kalashnikov AK-12 and AK-15 assault rifle (Russia)",
      "caliber": "7.62x39",
      "action": "Gas operated",
      "LengthFolded": "880-940 (690 with stock folded)",
      "BarrelLength": "415",
      "WeightEmpty": "3.5",
      "rounds": "30",
      "fireRate": "600-700",
      "effective": "Effective firing range	700",
      "classification": "Firearm",
    },
    {
      "id": 2,
      "stock": 4,
      "priceNow": 1024.99,
      "priceBefore": 1099.99,
      "title": "AN-94",
      "description": "The AN-94 is a Russian assault rifle. The initials stand for Avtomat Nikonova model of 1994, after its chief designer Gennadiy Nikonov, who previously worked on the Nikonov machine gun.",
      "completeDescription": "The most conspicuous identifying feature of the AN-94 is its magazine which is canted several degrees to the right of center (when viewed from a firing position). This design feature is necessary to accommodate the unique ammunition feed mechanism. The AN-94 is chambered in the same 5.45×39mm M74 cartridge as the AK-74, and it utilizes a rotating bolt to lock the action. Gennadiy Nikonov and his engineers used the Russian term Smeschennyi Impuls Svobodnogo Zatvora to describe the rifle's method of operation, meaning recoil shifted pulse. When a round is fired, residual energy from the propellant charge in the cartridge acts upon the safely locked breech and bolt carrier. Simultaneously, a quantity of powder gases driving the bullet through the barrel is tapped and acts upon the piston in the gas tube located above and parallel to the barrel.",
      "category": "assault-riffle",
      "img": "https://res.cloudinary.com/dndvrsb0w/image/upload/v1686697705/an-94-abakan-avtomat-an-94_0_p6sa45.jpg",
      "rate": "⭐⭐⭐⭐⭐",
      "credit": "Payments as low as $40.38 / month",
      "stockDetail": "Very Low Stock",
      "shipping": "Ships in 20 to 40 business days",
      "fullName": "Nikonov AN-94 Abakan assault rifle (Russia)",
      "caliber": "5.45x39 7N6 7N10 7N22 7N24",
      "action": "select-fire",
      "LengthFolded": "728",
      "BarrelLength": "405",
      "WeightEmpty": "3.85 (less magazine)",
      "rounds": "30",
      "fireRate": "600 / 1800",
      "effective": "Effective firing range 700",
      "classification": "Firearm",
    },
    {
      "id": 3,
      "stock": 3,
      "priceNow": 799.99,
      "priceBefore": 849.99,
      "title": "SCAR-H",
      "description": "The FN SCAR (Special Operations Forces Combat Assault Rifle) is a family of gas-operated short-stroke gas piston automatic rifles developed by Belgian manufacturer FN Herstal (FN) in 2004.",
      "completeDescription": "The FN SCAR Mk.20 Mod.0 SSR / Sniper Support Rifle is the latest offspring of the Special Forces Combat Assault Rifles (SCAR) family, developed for US Special Operations command (US SOCOM) by US-based subsidiary of the famous Belgian small arms-making company FN Herstal. The FN SCAR-SSR Mk.20 Mod.0 Sniper Support Rifle is based on the 7,62mm Mk.17 Mod.0 SCAR-H rifle, and is designed to provide accurate and rapid semi-automatic fire at ranges beyond capabilities of the standard 5,56mm assault rifles currently in service. It can be used as a Designated Marksman Rifle (DMR), as a tactical equivalent of the famous Russian Dragunov SVD rifle, or as a weapon for a 2nd member (spotter) of a conventional sniper team, where the 1st member is armed with long-range and precise, but relatively slow-firing weapon such as XM2010 ESR (hence the moniker “Sniper Support Rifle”).",
      "category": "assault-riffle",
      "img": "https://res.cloudinary.com/dndvrsb0w/image/upload/v1686697704/FN-SCAR-H-Mk2-full-auto-FDE_howwoc.png",
      "rate": "⭐⭐⭐",
      "credit": "Payments as low as $40.38 / month",
      "stockDetail": "Very Low Stock",
      "shipping": "Ships in 20 to 40 business days",
      "fullName": "FN SCAR",
      "caliber": "7,62×51 NATO (.308 Win)",
      "action": "Semi-automatic, gas operated",
      "LengthFolded": "1028 mm",
      "BarrelLength": "508 mm",
      "WeightEmpty": "5,05",
      "rounds": "20 rounds",
      "fireRate": "550–650 rounds/min",
      "effective": "500 m",
      "classification": "Firearm",
    },
    {
      "id": 4,
      "stock": 2,
      "priceNow": 549.99,
      "priceBefore": 699.99,
      "title": "M-16",
      "description": "The M16 Assault Rifle is the standard-issue shoulder weapon in the U.S. military. Designed to fire small, high-velocity rounds (5.56 mm caliber vs. 7.62 mm), the weapon is relatively small and light, thereby significantly decreasing the overall load warfighters needed to carry.",
      "completeDescription": "The M16 is a lightweight, 5.56 mm, air-cooled, gas-operated, magazine-fed assault rifle, with a rotating bolt. The M16's receivers are made of 7075 aluminum alloy, its barrel, bolt, and bolt carrier of steel, and its handguards, pistol grip, and buttstock of plastics. The M16 internal piston action was derived from the original ArmaLite AR-10 and ArmaLite AR-15 actions. This internal piston action system designed by Eugene Stoner is commonly called a direct impingement system, but it does not use a conventional direct impingement system. In U.S. Patent 2,951,424, the designer states: ″This invention is a true expanding gas system instead of the conventional impinging gas system.″ The gas system, bolt carrier, and bolt-locking design were novel for the time. ",
      "category": "assault-riffle",
      "img": "https://res.cloudinary.com/dndvrsb0w/image/upload/v1686697705/Homemade-M16-1.9.23_tgzkwy.jpg",
      "rate": "⭐",
      "credit": "Payments as low as $40.38 / month",
      "stockDetail": "Very Low Stock",
      "shipping": "Ships in 20 to 40 business days",
      "fullName": "M-16 rifle",
      "caliber": "5.56×45 mm NATO",
      "action": "Gas-operated",
      "LengthFolded": "986 mm",
      "BarrelLength": "508 mm",
      "WeightEmpty": "2.89 kg",
      "rounds": "30 rounds",
      "fireRate": "700–800 rounds/min",
      "effective": "550 m",
      "classification": "Firearm",
    },
    {
      "id": 5,
      "stock": 3,
      "priceNow": 599.99,
      "priceBefore": 649.99,
      "title": "P-90",
      "description": "The P90 is a selective fire, straight blowback-operated weapon with a cyclic rate of fire of around 850-1,100 rounds per minute. The weapon is chambered for FN's 5.7×28mm ammunition. Its unusual shape is based on extensive ergonomic research.",
      "completeDescription": "The FN P90 is a submachine gun chambered for the 5.7×28mm cartridge, also classified as a personal defense weapon designed and manufactured by FN Herstal in Belgium.Created in response to NATO requests for a replacement for 9×19mm Parabellum firearms, the P90 was designed as a compact but powerful firearm for vehicle crews, operators of crew-served weapons, support personnel, special forces, and counter-terrorist groups. Designed in conjunction with the FN Five-seven pistol and FN 5.7x28mm NATO ammunition, development of the weapon began in 1986, and production commenced in 1990, when it was known as the Project 9.0 (from which the 90 in its name is derived), whereupon the 5.7×28mm ammunition was redesigned and shortened. A modified version of the P90 with a magazine adapted to use the new ammunition was introduced in 1993, and the Five-seven pistol was subsequently introduced as a companion weapon using the same 5.7×28mm ammunition.",
      "category": "sub-machine-gun",
      "img": "https://res.cloudinary.com/dndvrsb0w/image/upload/v1686699019/weapons-fn-p90-wallpaper-preview_knjvwu.jpg",
      "rate": "⭐⭐⭐⭐⭐",
      "credit": "Payments as low as $40.38 / month",
      "stockDetail": "Very Low Stock",
      "shipping": "Ships in 20 to 40 business days",
      "fullName": "FN P90",
      "caliber": "5.7x28 FN",
      "action": "Straight blowback, closed bolt",
      "LengthFolded": "50.5 cm",
      "BarrelLength": "26.4 cm",
      "WeightEmpty": "2.6 kg",
      "rounds": "50 rounds",
      "fireRate": "850-1,100 rounds/min",
      "effective": "200 m",
      "classification": "Firearm",
    },
    {
      "id": 6,
      "stock": 5,
      "priceNow": 499.99,
      "priceBefore": 519.99,
      "title": "MP5",
      "description": "The MP5 belongs to the submachine gun class. It can spawn anywhere in a campaign, especially in safe rooms. It has a lower fire rate than the other Submachine Gun variants in the game, but to balance this, the MP5 has slightly higher accuracy than the other two submachine guns, whilst its damage per shot and fire rate are below that of the Silenced Submachine Gun. ",
      "completeDescription": "The Heckler und Koch MP5 submachine gun is perhaps the most famous and widespread firearm of its class to be developed since the Second World War. Development of the MP5 began circa 1964 under the company designation HK MP-54, or simply HK 54. In 1966, the West German Police and Border Guard (‘Bundesgrenzschutz’) adopted the HK 54, designating it as the MP5. It was originally available in two forms – MP5 with fixed buttstock and MP5A1 with retractable buttstock. Some years later HK slightly upgraded the design of the MP5, swapping the sights from flip-up open notch rear and blade front to drum-type diopter rear and hooded post front. The muzzle was also changed, the two slot muzzle compensator was changed to a three-lug QD silencer mount without a compensator. Other improvements made over that time concerned the magazines – early magazines were straight box type, later ones were of curved box type for improved reliability.",
      "category": "sub-machine-gun",
      "img": "https://res.cloudinary.com/dndvrsb0w/image/upload/v1686699019/p_sub1_210119071103_vqghqt.jpg",
      "rate": "⭐⭐⭐",
      "credit": "Payments as low as $40.38 / month",
      "stockDetail": "Very Low Stock",
      "shipping": "Ships in 20 to 40 business days",
      "fullName": "Heckler und Koch MP5 submachine gun (Germany)",
      "caliber": "7.62x51mm NATO",
      "action": "select-fire",
      "LengthFolded": "680 mm",
      "WeightEmpty": "2.54 kg",
      "BarrelLength": "225 mm",
      "rounds": "15-, 30-, 40-, or 50-rounds",
      "fireRate": "800 rounds/min",
      "effective": "200 m",
      "classification": "Firearm",
    },
    {
      "id": 7,
      "stock": 2,
      "priceNow": 599.99,
      "priceBefore": 619.99,
      "title": "PP-19",
      "description": "The Bizon is a lightweight selective fire weapon that fires from a closed bolt, a feature that enhances the gun's practical accuracy.[2] The weapon has a notably large magazine capacity. It is based on the AKS-74 and features a 60% parts commonality with the AK-74 assault rifle.",
      "completeDescription": "This interesting submachine gun had been developed in Izhevsk at the famous IZHMASH state arms factory during the early 1990s, and first appeared on public circa 1993. Obviously influenced by the somewhat unsuccessful Calico submachine guns, Bizon (Bison) SMG combined high capacity 'helical' magazine with more conventional appearance and layout. Bizon heavily based on AKS-74 assault rifle, and actually built on shortened AKS-74 receivers, with AKS-74 pistol grip, trigger unit and folding butt. Latter models introduced somewhat improved shape of pistol grip, with better ergonomics. Large capacity magazine is located under the barrel, and serves as a forearm, resulting in comfortable hold and trim profile. This firearm said to be comfortable to carry and fire, and provides a lot of firepower. Also, thanks to its closed bolt fire mode, combined with hammer fire control module, provides accurate semiautomatic fire.",
      "category": "sub-machine-gun",
      "img": "https://res.cloudinary.com/dndvrsb0w/image/upload/v1686699020/PP-19-01_Vityaz_at_Interpolitex-2016_01_ozh8dg.jpg",
      "rate": "⭐⭐⭐⭐⭐",
      "credit": "Payments as low as $40.38 / month",
      "stockDetail": "Very Low Stock",
      "shipping": "Ships in 20 to 40 business days",
      "fullName": "PP-19 Bizon",
      "caliber": "9x18mm PM and PMM",
      "action": "Blowback, closed bolt",
      "LengthFolded": "660 mm",
      "BarrelLength": "195 mm",
      "WeightEmpty": "2.1 kg",
      "rounds": "64 rounds",
      "fireRate": "600 – 700 rounds per minute",
      "effective": "100 – 200 meters",
      "classification": "Firearm",
    },
    {
      "id": 8,      
      "stock": 4,
      "priceNow": 589.99,
      "priceBefore": 599.99,
      "title": "MP7",
      "description": "The MP7 uses a short-stroke piston gas system as is used on H&K's G36 and HK416 in place of a blowback system traditionally seen on submachine guns.[10] The 4.6×30mm ammunition is exclusive to the gun and offers low recoil...",
      "completeDescription": "The HK MP7 Personal Defense Weapon (PDW) is a member of a relatively new class of small arms, called Personal Defense Weapons (PDW; such specialized weapons are build since the start ofWW2). The PDW are intended, as name implies, to be a defensive sidearm for second-line troops, vehicle crews and other military personnel who normally not issued with assault rifles. Previously, these troops were issued with pistols or submachine guns, but proliferation of bodyarmor in recent years made those guns ineffective. The first firearm, intended as “the new age PDW” and offered in that class was Belgian-made FNP90, and it had special low-impulse, high-velocity ammunition, capable of penetration of current military bodyarmor and helmets at ranges of 100 meters and beyond, while being much smaller and lighter, than assault rifle. The HK MP7, originally known simply as HK PDW, is another entry in the PDW class, and thus is a direct rival to FN P90.",
      "category": "sub-machine-gun",
      "img": "https://res.cloudinary.com/dndvrsb0w/image/upload/v1686699019/germany-the-gun-heckler-andamp-koch-mp7-wallpaper-preview_ijlxrr.jpg",
      "rate": "⭐⭐⭐⭐",
      "credit": "Payments as low as $40.38 / month",
      "stockDetail": "Very Low Stock",
      "shipping": "Ships in 20 to 40 business days",
      "fullName": "HK MP7 PDW",
      "caliber": "4.6x30 HK Heckler & Koch",
      "action": "select-fire",
      "LengthFolded": "540 mm",
      "BarrelLength": "180 mm",
      "WeightEmpty": "1.5 kg",
      "rounds": "20 - 40 rounds",
      "fireRate": "950 rounds per minute",
      "effective": "200 m",
      "classification": "Firearm",
    },
    {
      "id": 9,
      "stock": 4,
      "priceNow": 1399.99,
      "priceBefore": 1459.99,
      "title": "M2-49",
      "description": "The M249 is a belt-fed light-machine-gun. It fires the 5.56x45mm NATO cartridge, usually a combination of one M856 tracer and four M855 ball cartridges fed from M27 linked belts. Belts are typically held in a hard plastic or soft canvas box attached to the underside of the weapon. The M249 can also fire rifle grenades.",
      "completeDescription": "The M249 SAW light machine gun was developed by the famous Belgian company FN Herstal, in the late 1970’s and early 1980’s as the FN Minimi. Mass production began in 1982 in Belgium, and at about the same time it has been adopted by the US Armed forces as the M249 Squad Automatic Weapon (SAW). Since its introduction the Minimi has seen widespread service, and numerous variations have been developed. Firstly, the Para (Paratroop) version came out, with a shorter barrel and tubular telescoped buttstock. This gun traded off range and firepower for compactness and maneuverability. Quite recently, an SPW version was developed, which featured a Para-type buttstock, a barrel of intermediate length (between standard and Para models), and a Picatinny-type rail mount, which allows the mounting of a wide variety of sights and scopes. To save weight, the magazine feed option of the standard and para models has been discarded. This version, in a slightly modified form, was adopted by the US Special Forces Command (US SOCOM) as the Mk.46 model 0 light machine gun.",
      "category": "light-machine-gun",
      "img": "https://res.cloudinary.com/dndvrsb0w/image/upload/v1686697705/background-machine-gun-m249-saw-wallpaper-preview_uybnus.jpg",
      "rate": "⭐⭐⭐",
      "credit": "Payments as low as $40.38 / month",
      "stockDetail": "Very Low Stock",
      "shipping": "Ships in 20 to 40 business days",
      "fullName": "M249 SAW",
      "caliber": "5.56x45mm NATO",
      "action": "Gas-operated long-stroke piston",
      "LengthFolded": "1040 mm",
      "BarrelLength": "465 mm",
      "WeightEmpty": "7.1 kg",
      "rounds": "M27 linked disintegrating belt",
      "fireRate": "750 – 1000 rounds per minute",
      "effective": "700 m",
      "classification": "Firearm",
    },
    {
      "id": 10,
      "stock": 4,
      "priceNow": 1799.99,
      "priceBefore": 1849.99,
      "title": "M-134",
      "completeDescription": "The M134 Minigun is an American 7.62×51mm NATO six-barrel rotary machine gun with a high rate of fire (2,000 to 6,000 rounds per minute).[2] It features a Gatling-style rotating barrel assembly with an external power source, normally an electric motor. The 'Mini in the name is in comparison to larger-caliber designs that use a rotary barrel design, such as General Electric's earlier 20 mm M61 Vulcan, and 'gun' for the use of rifle ammunition as opposed to autocannon shells. 'Minigun' refers to a specific model of weapon that General Electric originally produced, but the term 'minigun has popularly come to refer to any externally powered rotary gun of rifle caliber. The term is sometimes used loosely to refer to guns of similar rates of fire and configuration, regardless of power source and caliber. ",
      "description": "The M134 Minigun is an American 7.62x51mm NATO six-barrel rotary machine gun with a high rate of fire (2,000 to 6,000 rounds per minute). It features a Gatling-style rotating barrel assembly with an external power source, normally an electric motor.",
      "category": "light-machine-gun",
      "img": "https://res.cloudinary.com/dndvrsb0w/image/upload/v1686697704/thumb-1920-169146_kgxw7u.jpg",
      "rate": "⭐⭐⭐⭐",
      "credit": "Payments as low as $40.38 / month",
      "stockDetail": "Very Low Stock",
      "shipping": "Ships in 20 to 40 business days",
      "fullName": "M134 Minigun",
      "caliber": "7.62×51mm NATO",
      "action": "Electrically driven rotary breech",
      "LengthFolded": "801.6 mm",
      "BarrelLength": "558.8 mm",
      "WeightEmpty": "39 kg",
      "rounds": "500-5,000-round belt",
      "fireRate": "Variable, 2,000–6,000 rpm",
      "effective": "1,000 m",
      "classification": "Firearm",
    },
    {
      "id": 11,
      "stock": 5,
      "priceNow": 1999.99,
      "priceBefore": 2199.99,
      "title": "AUG-HBAR",
      "description": "The Steyr AUG is a selective-fire, bullpup assault rifle with a conventional gas-piston-operated action that fires from a closed bolt. It is designed as a Modular Weapon System that could be quickly configured as an assault rifle, a carbine, a submachine gun and even an open-bolt light-machine-gun. ",
      "completeDescription": "The Steyr AUG is an Austrian bullpup assault rifle chambered for the 5.56×45mm NATO intermediate cartridge, designed in the 1960s by Steyr-Daimler-Puch, and now manufactured by Steyr Arms GmbH & Co KG. It was adopted by the Austrian Army in 1977 as the StG 77 (Sturmgewehr 77), where it replaced the 7.62×51mm NATO StG 58 automatic rifle.In production since 1977, it is the standard small arm of the Bundesheer and various Austrian federal police units, and its variants have also been adopted by the armed forces of dozens of countries, with some using it as a standard-issue service rifle. Steyr AUG importation into the United States began in the 1980s as the AUG/SA (SA denoting semiautomatic). President George H.W. Bush banned the AUG via an executive order under the 1989 Assault Weapon Import Ban. Six years into the ban, AUG buyers gained a reprieve as cosmetic changes to the carbine's design allowed importation once again. Changes included the pistol grip being changed into a thumbhole stock, and the gun barrel left unthreaded to prevent attachment of flash hiders and suppressors. ",
      "category": "light-machine-gun",
      "img": "https://res.cloudinary.com/dndvrsb0w/image/upload/v1686697704/xzycumaiff541_jcy88c.jpg",
      "rate": "⭐⭐⭐⭐⭐",
      "credit": "Payments as low as $40.38 / month",
      "stockDetail": "Very Low Stock",
      "shipping": "Ships in 20 to 40 business days",
      "fullName": "Steyr AUG",
      "caliber": "5.56×45mm NATO",
      "action": "Gas-operated, rotating bolt",
      "LengthFolded": "900 mm",
      "BarrelLength": "621 mm",
      "WeightEmpty": "4.9 kg",
      "rounds": "30-, 42-rounds",
      "fireRate": "650–720 rounds/min",
      "effective": "300 m",
      "classification": "Firearm",
    },
    {
      "id": 12,
      "stock": 2,
      "priceNow": 1649.99,
      "priceBefore": 1699.99,
      "title": "RPK",
      "description": "The RPK functions identically to the AK-47. It also uses the same 7.62x39mm ammunition. It has a similar design layout to the Kalashnikov series of rifles, with modifications to increase the RPK's effective range and accuracy, enhance its sustained fire capability, and strengthen the receiver.",
      "completeDescription": "The RPK features a thicker and longer barrel than the AKM. This allows for it to be fired for longer without permanent loss in accuracy due to the barrel heating up. The chrome-lined barrel is permanently fixed to the receiver and cannot be replaced in the field. It is fitted with a new front sight base, and the gas block lacks both a bayonet lug and an under-barrel cleaning rod guide. The barrel also features a folding bipod mounted near the muzzle, and a front sight base with a lug that limits the bipod's rotation around the axis of the barrel. The barrel has a threaded muzzle, enabling the use of muzzle devices such as flash hiders, compensators, and blank-firing adapters. When a muzzle device is not being used, the threads on the muzzle can be covered by a thread protector. The barrel is pinned to the receiver in a modified trunnion, reinforced by ribbing, and is slightly wider than the trunnion used on the standard AKM type rifles. Symmetrical bulges on both sides of the front trunnion ensure a proper fit inside the receiver. ",
      "category": "light-machine-gun",
      "img": "https://res.cloudinary.com/dndvrsb0w/image/upload/v1686697704/zastava_m72_rpk_uxfv09.jpg",
      "rate": "⭐⭐⭐⭐⭐",
      "credit": "Payments as low as $40.38 / month",
      "stockDetail": "Very Low Stock",
      "shipping": "Ships in 20 to 40 business days",
      "fullName": "RPK",
      "caliber": "7.62×39mm M43",
      "action": "Gas operated, rotating bolt",
      "LengthFolded": "1,040 mm",
      "BarrelLength": "590 mm",
      "WeightEmpty": "4.8 kg",
      "rounds": "30-, 40-round curved magazine",
      "fireRate": "600 rounds/min",
      "effective": "100–1,000 m",
      "classification": "Firearm",
    },
    {
      "id": 13,
      "stock": 5,
      "priceNow": 2199.99,
      "priceBefore": 2299.99,
      "title": "SPAS-12",
      "description": "The SPAS-12 was designed to function primarily in semi-automatic mode, with the pump-action mode used to reliably fire low-pressure ammunition such as tear gas rounds or less-lethal bean bags.",
      "completeDescription": "The SPAS-12 was designed to function primarily in semi-automatic mode, with the pump-action mode used to reliably fire low-pressure ammunition such as tear gas rounds or less-lethal bean bags. The firing mode is switched by depressing the button under the fore-grip and also sliding it forwards or backwards until it clicks into position allowing the rotating sleeve to open or close the two gas ports. The semi-automatic mode functions with a short-stroke gas piston system. When a shell is fired, the pressure makes the bolt move rearward but the bolt will stop before opening as it deploys a single top locking lug. The gas vents into the barrel and the gas port is located towards the end of the barrel. From the gas port, the gas vents downwards into the gas block where it pushes the piston rearward. Because of the presence of the magazine tube and to avoid the use of a top-mounted gas system, the gas block and the piston are annular, along with the piston spring they enclose the magazine tube. Once operated, the piston drives 2 symmetrical thin sprung operating rods located in the corners formed by the barrel and the magazine tube. As the rods push the bolt carrier rearward, it disengages the locking lug and drives the bolt rearward, allowing the system to cycle. ",
      "category": "shotgun",
      "img": "https://res.cloudinary.com/dndvrsb0w/image/upload/v1686697706/Franchi_SPAS_12_Grip_Safety_o6bh3w.jpg",
      "rate": "⭐⭐⭐",
      "credit": "Payments as low as $40.38 / month",
      "stockDetail": "Very Low Stock",
      "shipping": "Ships in 20 to 40 business days",
      "fullName": "Franchi SPAS-12",
      "caliber": "12 gauge",
      "action": "Pump-action/gas-operated",
      "LengthFolded": "1041 mm",
      "BarrelLength": "18',19-7/8'",
      "WeightEmpty": "4.4 kg",
      "rounds": "Tube Extension 6+1",
      "fireRate": "Semi-automatic or pump action",
      "effective": "Dependent on ammunition used",
      "classification": "Firearm",
    },
    {
      "id": 14,
      "stock": 5,
      "priceNow": 2599.99,
      "priceBefore": 2649.99,
      "title": "AA-12",
      "description": "The AA-12 (Auto Assault-12), originally designed and known as the Atchisson Assault Shotgun, is an automatic combat shotgun developed in 1972 by Maxwell Atchisson ",
      "completeDescription": "The AA-12 (Auto Assault-12), originally designed and known as the Atchisson Assault Shotgun, is an automatic combat shotgun developed in 1972 by Maxwell Atchisson (however, the original development by Atchisson seems to have produced only a few guns at prototype-level, with the development that ultimately lead to the gun entering the market being done later by Military Police Systems, Inc.[5]). The most prominent feature is reduced recoil. The current 2005 version has been developed over 18 years since the patent was sold to Military Police Systems, Inc. The original design was the basis of several later weapons, including the USAS-12 combat shotgun. The shotgun fires in fully automatic mode only. However, the relatively low cyclic rate of fire of around 300 rounds per minute enables the shooter to fire semi-automatically de facto with brief trigger pulls. It is fed from either an 8-shell box magazine or a 20-shell drum magazine.",
      "category": "shotgun",
      "img": "https://res.cloudinary.com/dndvrsb0w/image/upload/v1686697706/AA12-Right-1_let5lh.jpg",
      "rate": "⭐⭐⭐⭐⭐",
      "credit": "Payments as low as $40.38 / month",
      "stockDetail": "Very Low Stock",
      "shipping": "Ships in 20 to 40 business days",
      "fullName": "Atchisson AA-12",
      "caliber": "12 Gauge",
      "action": "	API blowback",
      "LengthFolded": "991 mm",
      "BarrelLength": "457 mm",
      "WeightEmpty": "7.3 kg",
      "rounds": "8-, 20-, 32 rounds",
      "fireRate": "300 rounds/mi",
      "effective": "Dependent on ammunition used",
      "classification": "Firearm",
    },
    {
      "id": 15,
      "stock": 1,
      "priceNow": 2349.99,
      "priceBefore": 2599.99,
      "title": "BENELLI-M4",
      "description": "The Benelli M4 is a semi-automatic shotgun produced by Italian firearm manufacturer Benelli Armi SpA, and the fourth and last model of the Benelli Super 90 line of semi-automatic shotguns. ",
      "completeDescription": "The Benelli M4 is a semi-automatic shotgun produced by Italian firearm manufacturer Benelli Armi SpA, and the fourth and last model of the Benelli Super 90 line of semi-automatic shotguns. The M4 uses a proprietary action design called the 'auto-regulating gas-operated' (ARGO) system, which was created specifically for the weapon. Designed in 1998, the M4 was adopted by the armed forces of Italy, the United States, and United Kingdom, among others, and has been used in a variety of conflicts. ",
      "category": "shotgun",
      "img": "https://res.cloudinary.com/dndvrsb0w/image/upload/v1686697705/Benelli-M4-4-1024x567_y1xkky.jpg",
      "rate": "⭐⭐⭐⭐",
      "credit": "Payments as low as $40.38 / month",
      "stockDetail": "Very Low Stock",
      "shipping": "Ships in 20 to 40 business days",
      "fullName": "Benelli M4",
      "caliber": "12-gauge",
      "action": "	Gas-operated, rotating bolt",
      "LengthFolded": "889 mm",
      "BarrelLength": "470 mm",
      "WeightEmpty": "3.82 kg",
      "rounds": "7+1 tubular magazine",
      "fireRate": "Semi-automatic",
      "effective": "50 m",
      "classification": "Firearm",
    },
    {
      "id": 16,
      "stock": 2,
      "priceNow": 3199.99,
      "priceBefore": 3299.99,
      "title": "Saiga-12",
      "description": "The Saiga-12 is a shotgun available in a wide range of configurations, patterned after the Kalashnikov series of rifles and named after the Saiga antelope native to Russia.",
      "completeDescription": "The Saiga-12 is a shotgun available in a wide range of configurations, patterned after the Kalashnikov series of rifles and named after the Saiga antelope native to Russia. Like the Kalashnikov rifle variants, it is a rotating bolt, long-stroke gas piston operated firearm that feeds from a square magazine. All Saiga-12 configurations are recognizable as Kalashnikov-pattern guns by the large lever-safety on the right side of the receiver, the optic mounting rail on the left side of the receiver and the large top-mounted dust cover held in place by the rear of the recoil spring assembly. Saiga firearms are meant for civilian domestic sale in Russia, and export to international markets. The Saiga-12 is manufactured by the Kalashnikov Concern (the merger of Izhmash and Izhevsk), in Russia. Kalashnikov Concern also manufactures Saiga 20s and Saiga 410s in 20-gauge and .410 bore, as well as the Saiga semi-automatic hunting rifles in a number of centerfire calibers. Russian armed forces use a combat shotgun variant called the KSK (Karabin Spetsialniy Kalahnikov, 'Kalashnikov Special Carbine'), with the 12-gauge size expressed in its metric equivalent of 18.5 mm. The Picatinny rail layout is similar to the civilian 030 version. ",
      "category": "shotgun",
      "img": "https://res.cloudinary.com/dndvrsb0w/image/upload/v1686697706/SDM_AK-12s_Tactical_shotgun_3_bv5u8y.jpg",
      "rate": "⭐⭐⭐⭐⭐",
      "credit": "Payments as low as $40.38 / month",
      "stockDetail": "Very Low Stock",
      "shipping": "Ships in 20 to 40 business days",
      "fullName": "Saiga-12",
      "caliber": "12-gauge, 20-gauge, .410",
      "action": "	Gas-operated, rotating bolt",
      "LengthFolded": "1145 mm",
      "BarrelLength": "580 mm ",
      "WeightEmpty": "3.6 kg",
      "rounds": "2, 5, 8, and 10-rounds",
      "fireRate": "Semi-automatic ",
      "effective": "150 m",
      "classification": "Firearm",
    },
    {
      "id": 17,
      "stock": 2,
      "priceNow": 4999.99,
      "priceBefore": 5999.99,
      "title": "Barret.50cal",
      "description": "The M82 is a short-recoil semi-automatic firearm. When the gun is fired, the barrel initially recoils for a short distance (about 1 inch (25 mm)), while being securely locked by the rotating bolt...",
      "completeDescription": "The Barrett M82 (standardized by the U.S. military as the M107) is a recoil-operated, semi-automatic anti-materiel rifle developed by the American company Barrett Firearms Manufacturing. Also called the Light Fifty (due to its chambering of the .50 BMG 12.7×99mm NATO cartridge), the weapon is classified in three variants: the original M82A1 (and M82A3) models, the bullpup M82A2 model, and the Barrett M107A1, with an attached muzzle brake (designed to accept a suppressor, and made out of titanium instead of steel). The M82A2 is no longer manufactured, though the XM500 can be seen as its successor. Despite being designated as an anti-materiel rifle, the M82 can also be deployed as an anti-personnel system.",
      "category": "sniper",
      "img": "https://res.cloudinary.com/dndvrsb0w/image/upload/v1686697704/3rngH4_k6bttr.png",
      "rate": "⭐⭐⭐⭐⭐",
      "credit": "Payments as low as $40.38 / month",
      "stockDetail": "Very Low Stock",
      "shipping": "Ships in 20 to 40 business days",
      "fullName": "Barrett M82",
      "caliber": ".50 caliber",
      "action": "	Recoil-operated, rotating bolt",
      "LengthFolded": "120 cm",
      "BarrelLength": "51 cm",
      "WeightEmpty": "13.5 kg",
      "rounds": "5- or 10-round detachable box",
      "fireRate": "Semi-automatic ",
      "effective": "1,800 m",
      "classification": "Firearm",
    },
    {
      "id": 18,
      "stock": 3,
      "priceBefore": 4899.99,
      "priceNow": 4599.99,
      "title": "T-5000",
      "description": "The Orsis T-5000 is a Russian bolt-action sniper rifle. It was the first product developed by ORSIS, and is produced in their Moscow factory. The rifle was introduced in 2011 at the international exhibition of Russian weapons in Nizhny Tagil, and is entirely original, using no third-party components.",
      "completeDescription": "In its standard configuration the T-5000 is equipped with a 660 mm fluted, stainless steel barrel (698 mm when chambered in .338 Lapua Magnum), cut to a twist rate between 1-in-10 and 1-in-12 depending on customer requirements. The stainless steel stock adopts a highly 'skeletal' design, with highly adjustable butt and cheekpiece components mounted on a folding stock that reduces the transport length of the T-5000 by around 250 mm. The trigger is adjustable from 500 g in its Varmint configuration, to over 1500 g depending on application, and a Picatinny rail is provided for the attachment of optics. ",
      "category": "sniper",
      "img": "https://res.cloudinary.com/dndvrsb0w/image/upload/v1686697705/ORSIS_yuy5gy.jpg",
      "rate": "⭐⭐⭐⭐",
      "credit": "Payments as low as $40.38 / month",
      "stockDetail": "Very Low Stock",
      "shipping": "Ships in 20 to 40 business days",
      "fullName": "Orsis T-5000",
      "caliber": "Various",
      "action": "	Bolt-action",
      "LengthFolded": "1,230 mm",
      "BarrelLength": "673.1 mm",
      "WeightEmpty": "6.3 kg ",
      "rounds": "5-rounds",
      "fireRate": "Semi-automatic",
      "effective": "1,000 m",
      "classification": "Firearm",
    },
    {
      "id": 19,
      "stock": 5,
      "priceNow": 4199.99,
      "priceBefore": 4699.99,
      "title": "R93",
      "description": "The Blaser R93 Tactical is a German bolt action sniper rifle, based on the Blaser R93 design. It has as variants the Blaser LRS 2 and Tactical 2. It is used by German and Dutch police forces as well as the Australian military and special police units. ",
      "completeDescription": "The LRT (Long Range Tactical), LRS 2 (Long Range Sporter 2) and Tactical 2 rifles are straight-pull bolt-action take down sniper rifles. The straight-pull action design was introduced in the Blaser R93 hunting rifle line. These actions allows for faster follow-up shots compared to traditional turn bolt actions. The rifles are designed to fire small groups (sub 0.07 mrad (7 mm at 100 m; 0.25 moa) with factory match ammunition. The LRS 2 version, comes chambered in .223 Remington, 6mm Norma BR, 6.5×55mm, .308 Winchester and .300 Winchester Magnum. An uncommon part of its design is that it is a straight-pull bolt-action rather than a turn-bolt, which allows for much faster follow-up shots. The 14-lug radial collet ensures the centering of the cartridge when fed into the chamber assisting in its accuracy. Barrel changes by an experienced person can take place in under 60 seconds. ",
      "category": "sniper",
      "img": "https://res.cloudinary.com/dndvrsb0w/image/upload/v1686697705/fa_sr_r93_o1_n3s1dc.jpg",
      "rate": "⭐⭐⭐⭐",
      "credit": "Payments as low as $40.38 / month",
      "stockDetail": "Very Low Stock",
      "shipping": "Ships in 20 to 40 business days",
      "fullName": "Blaser R93 Tactical",
      "caliber": "	7.62x51mm NATO",
      "action": "Straight-pull bolt action",
      "LengthFolded": "?",
      "BarrelLength": "25'",
      "WeightEmpty": "5.4 kg",
      "rounds": "5-round box magazine",
      "fireRate": "Semi-automatic",
      "effective": "1000 m",
      "classification": "Firearm",
    },
    {
      "id": 20,
      "stock": 2,
      "priceNow": 4599.99,
      "priceBefore": 4999.99,
      "title": "AWM",
      "description": "The AWM is a bolt-action sniper rifle manufactured by Accuracy International designed for magnum rifle cartridges. The Accuracy International AWM is also unofficially known as the AWSM (Arctic Warfare Super Magnum), which typically denotes AWM rifles chambered in .338 Lapua Magnum. ",
      "completeDescription": "The Accuracy International AWM sniper rifle is a variant of the British Accuracy International Arctic Warfare (AW) rifle that was the basis of a family of sniper rifles using the Arctic Warfare name. As such the design details of the AWM variant are similar to the ones found in the basic AW rifle system. Compared to the AW, the AWM has a longer bolt to accommodate larger magnum-length cartridges such as the .300 Winchester Magnum and the .338 Lapua Magnum. The bolt head, locking ring, and extractor and magazines were also revised to work with the increased size and operating pressures of magnum rifle cartridges. The AWM features a detachable single stack removable box magazine which holds five rounds. The normal cartridges for this rifle, and the ones which have been accepted by NATO for use in AWM rifles, are .300 Winchester Magnum and .338 Lapua Magnum. ",
      "category": "sniper",
      "img": "https://res.cloudinary.com/dndvrsb0w/image/upload/v1686697705/maxresdefault_pyssyh.jpg",
      "rate": "⭐⭐⭐",
      "credit": "Payments as low as $40.38 / month",
      "stockDetail": "Very Low Stock",
      "shipping": "Ships in 20 to 40 business days",
      "fullName": "Accuracy International AWM",
      "caliber": "	.300 Winchester, Magnum .338 ",
      "action": "	Bolt-action",
      "LengthFolded": "1,270 mm",
      "BarrelLength": "686 mm",
      "WeightEmpty": "6.9 kg",
      "rounds": "5-round box magazine",
      "fireRate": "Semi-automatic",
      "effective": "1,100 m",
      "classification": "Firearm",
    }
]; */