const TYPES_CRUD = {
  CREATE_DATA: "CREATE_DATA",
  READ_ALL_DATA: "READ_ALL_DATA",
  UPDATE_DATA: "UPDATE_DATA",
  DELETE_DATA: "DELETE_DATA",
  NO_DATA: "NO_DATA",
};

const TYPES_CONTADOR = {
  INCREMENT: "INCREMENT",
  INCREMENT_5: "INCREMENT_5",
  DECREMENT: "DECREMENT",
  DECREMENT_5: "DECREMENT_5",
  RESET: "RESET",
};

const TYPES_SHOPPING = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_ONE_FROM_CART: "REMOVE_ONE_FROM_CART",
  REMOVE_ALL_FROM_CART: "REMOVE_ALL_FROM_CART",
  CLEAR_CART: "CLEAR_CART",
};

export {TYPES_CRUD, TYPES_CONTADOR, TYPES_SHOPPING}